version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=5000
  redis:
    image: redis
